const celestial_bodies = {
    Sun: {
        Name: "Sun",
        Distance: 1,
        Radius: 696340,
        Color: "yellow",
        type: "star",
        diameter_km: 1391016,
        spectral_type: "G2V",
        distance_from_earth_km: 149600000,
        mass: 1.989e30,
        dominant_element1: "hydrogen",
        dominant_element2: "helium"
    },
    Mercury: {
        Name: "Mercury",
        type: "solid planet",
        diameter_km: 4879,
        orbital_period_days: 88,
        moons: 0,
        radius_km: 2439.7,
        distance_from_sun_km: 57910000,
        AU: 0.39,
        surface_temperature_c: 167,
        atmosphere_composition: ["oxygen", "sodium", "hydrogen", "helium", "potassium"],
        distance_from_earth_km: 91700000,
        axis_rotation_period_hours: 1407.6,
        color: "gray"
    },
    Venus: {
        Name: "Venus",
        type: "solid planet",
        diameter_km: 12104,
        orbital_period_days: 225,
        moons: 0,
        radius_km: 6051.8,
        distance_from_sun_km: 108200000,
        AU: 0.72,
        surface_temperature_c: 464,
        atmosphere_composition: ["carbon_dioxide", "nitrogen", "sulfur_dioxide"],
        distance_from_earth_km: 41400000,
        axis_rotation_period_hours: 2802,
        color: "yellow"
    },
    Earth: {
        Name: "Earth",
        type: "solid planet",
        diameter_km: 12742,
        orbital_period_days: 365.25,
        moons: 1,
        radius_km: 6371,
        distance_from_sun_km: 149600000,
        AU: 1.0,
        surface_temperature_c: 15,
        atmosphere_composition: ["nitrogen", "oxygen", "argon"],
        distance_from_earth_km: 0,
        axis_rotation_period_hours: 24,
        color: "blue"
    },
    Mars: {
        Name: "Mars",
        type: "solid planet",
        diameter_km: 6779,
        orbital_period_days: 687,
        moons: 2,
        radius_km: 3389.5,
        distance_from_sun_km: 227900000,
        AU: 1.52,
        surface_temperature_c: -63,
        atmosphere_composition: ["carbon_dioxide", "nitrogen", "argon"],
        distance_from_earth_km: 55800000,
        axis_rotation_period_hours: 24.6,
        color: "red"
    },
    Jupiter: {
        Name: "Jupiter",
        type: "gas giant",
        diameter_km: 139820,
        orbital_period_days: 4333,
        moons: 79,
        radius_km: 69911,
        distance_from_sun_km: 778500000,
        AU: 5.20,
        surface_temperature_c: -108,
        atmosphere_composition: ["hydrogen", "helium", "methane"],
        distance_from_earth_km: 628730000,
        axis_rotation_period_hours: 9.9,
        color: "brown"
    },
    Saturn: {
        Name: "Saturn",
        type: "gas giant",
        diameter_km: 116460,
        orbital_period_days: 10759,
        moons: 83,
        radius_km: 58232,
        distance_from_sun_km: 1429400000,
        AU: 9.58,
        surface_temperature_c: -178,
        atmosphere_composition: ["hydrogen", "helium", "methane"],
        distance_from_earth_km: 1200000000,
        axis_rotation_period_hours: 10.7,
        color: "golden"
    },
    Uranus: {
        Name: "Uranus",
        type: "ice giant",
        diameter_km: 50724,
        orbital_period_days: 30687,
        moons: 27,
        radius_km: 25362,
        distance_from_sun_km: 2871000000,
        AU: 19.18,
        surface_temperature_c: -224,
        atmosphere_composition: ["hydrogen", "helium", "methane"],
        distance_from_earth_km: 2723950000,
        axis_rotation_period_hours: 17.2,
        color: "cyan"
    },
    Neptune: {
        Name: "Neptune",
        type: "ice giant",
        diameter_km: 49244,
        orbital_period_days: 60190,
        moons: 14,
        radius_km: 24622,
        distance_from_sun_km: 4495000000,
        AU: 30.07,
        surface_temperature_c: -214,
        atmosphere_composition: ["hydrogen", "helium", "methane"],
        distance_from_earth_km: 4351000000,
        axis_rotation_period_hours: 16.1,
        color: "blue"
    },
    Pluto: {
        Name: "Pluto",
        type: "dwarf planet",
        diameter_km: 2376,
        orbital_period_days: 90560,
        moons: 5,
        radius_km: 1188.3,
        distance_from_sun_km: 5906000000,
        AU: 39.48,
        surface_temperature_c: -229,
        atmosphere_composition: ["nitrogen", "methane", "carbon_monoxide"],
        distance_from_earth_km: 5906000000,
        axis_rotation_period_hours: 153.3,
        color: "brown"
    }
};

export default celestial_bodies;