const celestial_bodies = {
    Sun: {
        Name: "Sun",
        Nickname: "The Solar Dynamo",
        Distance: 1,
        Radius: 696340,
        Color: "yellow",
        type: "star",
        diameter_km: 1391016,
        spectral_type: "G2V",
        distance_from_earth_km: 149600000,
        mass: 1.989e30,
        dominant_element1: "hydrogen",
        dominant_element2: "helium",
        description: "The Sun is the heart of our solar system, a blazing ball of hot plasma that provides the energy necessary for life on Earth. It is a G-type main-sequence star (G2V) and is composed primarily of hydrogen (about 74%) and helium (about 24%), with trace amounts of heavier elements. The Sun's immense gravity holds the solar system together, keeping the planets in their orbits. It has a diameter of about 1.39 million kilometers and a mass of approximately 1.989 x 10^30 kilograms, making it by far the largest object in our solar system. The Sun's energy is produced through nuclear fusion in its core, where hydrogen atoms are fused into helium, releasing an enormous amount of energy in the process. This energy travels through space and reaches Earth as sunlight, which warms our planet and drives weather patterns, ocean currents, and photosynthesis in plants. The Sun has been shining for about 4.6 billion years and is expected to continue shining for another 5 billion years before it exhausts its fuel and evolves into a red giant."
    },
    Mercury: {
        Name: "Mercury",
        Nickname: "The Swift Planet",
        type: "solid planet",
        diameter_km: 4879,
        orbital_period_days: 88,
        moons: 0,
        radius_km: 2439.7,
        distance_from_sun_km: 57910000,
        AU: 0.39,
        surface_temperature_c: 167,
        atmosphere_composition: ["oxygen", "sodium", "hydrogen", "helium", "potassium"],
        distance_from_earth_km: 91700000,
        axis_rotation_period_hours: 1407.6,
        color: "gray",
        description: "Mercury is the first planet in our solar system, toasting comfortably as the closest planet to the Sun. It boasts an amazing surface temperature range, swinging from scorching highs of 430°C during the day to freezing lows of -180°C at night. With its swift 88-day orbit, Mercury zips around the Sun faster than any other planet, earning it the nickname 'The Swift Planet.' Despite its proximity to the Sun, Mercury has no moons and a very thin atmosphere, making it a fascinating world of extremes. It was named Mercury after the Roman messenger god, known for his speed and agility, perfectly fitting for this speedy planet."
    },
    Venus: {
        Name: "Venus",
        Nickname: "The Morning/Evening Star",
        type: "solid planet",
        diameter_km: 12104,
        orbital_period_days: 225,
        moons: 0,
        radius_km: 6051.8,
        distance_from_sun_km: 108200000,
        AU: 0.72,
        surface_temperature_c: 464,
        atmosphere_composition: ["carbon_dioxide", "nitrogen", "sulfur_dioxide"],
        distance_from_earth_km: 41400000,
        axis_rotation_period_hours: 2802,
        color: "yellow",
        description: "Venus, often called the 'Morning Star' or 'Evening Star' due to its bright visibility during dawn and dusk, is the second planet from the Sun. Named after the Roman goddess of love and beauty, Earth's Twin has a diameter of 12,104 km and an orbital period of 225 days. Venus is a solid planet with no moons, and has an extremely hot surface temperature of 464°C due to its thick atmosphere composed mainly of carbon dioxide, with traces of nitrogen and sulfur dioxide. The distance from Earth to Venus can be as close as 41.4 million km, making it one of our closest planetary neighbors. Venus rotates very slowly on its axis, taking about 2802 hours to complete one rotation, and it rotates in the opposite direction to most planets in our solar system. This also means that a year is longer than a day is on Venus!"
    },
    Earth: {
        Name: "Earth",
        Nickname: "Eden's Garden",
        type: "solid planet",
        diameter_km: 12742,
        orbital_period_days: 365.25,
        moons: 1,
        radius_km: 6371,
        distance_from_sun_km: 149600000,
        AU: 1.0,
        surface_temperature_c: 15,
        atmosphere_composition: ["nitrogen", "oxygen", "argon"],
        distance_from_earth_km: 0,
        axis_rotation_period_hours: 24,
        color: "blue",
        description: "Earth, our home planet, is the third planet from the Sun and the only known celestial body to support life. Like, in the universe. Referred to by many names throughout history, our home has been revered for its abundant natural beauty and life-sustaining environment. Earth has a diameter of 12,742 km and an orbital period of 365.25 days. It is a solid planet with one moon, and boasts a diverse range of climates and ecosystems. The average surface temperature is around 15°C, making it hospitable for a wide variety of life forms. Earth's atmosphere is primarily composed of nitrogen and oxygen, with traces of argon and other gases. The planet's distance from the Sun is about 149.6 million km, or 8 light minutes. It rotates on its axis every 24 hours, giving us our day-night cycle. Earth is a vibrant blue marble in the vastness of space, teeming with life and natural wonders. We are lucky enough to possess some of the rarest and most precious resources in the universe like our trees and abundant water."
    },
    Mars: {
        Name: "Mars",
        Nickname: "The Red Planet",
        type: "solid planet",
        diameter_km: 6779,
        orbital_period_days: 687,
        moons: 2,
        radius_km: 3389.5,
        distance_from_sun_km: 227900000,
        AU: 1.52,
        surface_temperature_c: -63,
        atmosphere_composition: ["carbon_dioxide", "nitrogen", "argon"],
        distance_from_earth_km: 55800000,
        axis_rotation_period_hours: 24.6,
        color: "red",
        description: "Mars, the fourth planet from the Sun, is often called the 'Red Planet' due to its reddish appearance caused by iron oxide (rust) on its surface. Named after the Roman god of war, Mars has a diameter of 6,779 km and an orbital period of 687 days. It is a solid planet with two small moons, Phobos and Deimos. The average surface temperature on Mars is around -63°C, making it a cold and inhospitable world. Its atmosphere is thin and composed mostly of carbon dioxide, with traces of nitrogen and argon. The distance from Earth to Mars can vary greatly, but at its closest approach, it is about 55.8 million km away. Mars rotates on its axis every 24.6 hours, giving it a day length similar to Earth's. Despite its harsh conditions, Mars has been a prime target for exploration due to evidence of past water flow and the potential for microbial life. As we continue to explore Mars and discover its history, we hope to eventually find evidence of past life and perhaps even establish a human presence on the Red Planet in the future."
    },
    Jupiter: {
        Name: "Jupiter",
        Nickname: "The Gas Giant",
        type: "gas giant",
        diameter_km: 139820,
        orbital_period_days: 4333,
        moons: 79,
        radius_km: 69911,
        distance_from_sun_km: 778500000,
        AU: 5.20,
        surface_temperature_c: -108,
        atmosphere_composition: ["hydrogen", "helium", "methane"],
        distance_from_earth_km: 628730000,
        axis_rotation_period_hours: 9.9,
        color: "brown",
        description: "Jupiter, the largest planet in our solar system, is a gas giant known for its massive size and iconic Great Red Spot, a giant storm that has been raging for centuries. Named after the king of the Roman gods, Jupiter has a diameter of 139,820 km and an orbital period of 4333 days. It has a staggering number of moons, with 79 confirmed satellites orbiting it. The average surface temperature on Jupiter is around -108°C, with an average wind speed of 360 km/h to match! Its atmosphere is primarily composed of hydrogen and helium, with traces of methane and other gases. The distance from Earth to Jupiter can vary greatly, but at its closest approach, it is about 628.73 million km away. The fastest trip made by a spacecraft to Jupiter took just under 13 months. Jupiter rotates on its axis every 9.9 hours, giving it the shortest day of any planet in our solar system. Despite being a gas giant with no solid surface, Jupiter's immense gravity has a significant influence on the orbits of other celestial bodies in the solar system, and it has been a key target for exploration due to its complex atmosphere and diverse moons."
    },
    Saturn: {
        Name: "Saturn",
        Nickname: "The Ringed Jewel of the Solar System",
        type: "gas giant",
        diameter_km: 116460,
        orbital_period_days: 10759,
        moons: 83,
        radius_km: 58232,
        distance_from_sun_km: 1429400000,
        AU: 9.58,
        surface_temperature_c: -178,
        atmosphere_composition: ["hydrogen", "helium", "methane"],
        distance_from_earth_km: 1200000000,
        axis_rotation_period_hours: 10.7,
        color: "golden",
        description: "Saturn, the sixth planet from the Sun, is renowned for its stunning ring system, which is the most extensive and complex in our solar system. Named after the Roman god of agriculture and time, Saturn has a diameter of 116,460 km and an orbital period of 10,759 days. It is a gas giant with 83 confirmed moons, including Titan, Enceladus, Rhea and Hyperion. These moons vary in size and composition, with Titan being the largest one, possessing unique methane rain. The average surface temperature on Saturn is around -178°C, and its atmosphere is primarily composed of hydrogen and helium, with traces of methane and other gases. Saturn's north pole possesses a strange, hexagonical storm that is twice as wide as the Earth itself! Saturn rotates on its axis every 10.7 hours, giving it a day length that is just under half of Earth's. The planet's iconic rings are made up of countless small particles of ice and rock, ranging in size from tiny grains to large boulders. Saturn's unique beauty and fascinating characteristics have made it a popular target for exploration and study in our quest to understand the wonders of our solar system."
    },
    Uranus: {
        Name: "Uranus",
        Nickname: "The Ice Giant",
        type: "ice giant",
        diameter_km: 50724,
        orbital_period_days: 30687,
        moons: 27,
        radius_km: 25362,
        distance_from_sun_km: 2871000000,
        AU: 19.18,
        surface_temperature_c: -224,
        atmosphere_composition: ["hydrogen", "helium", "methane"],
        distance_from_earth_km: 2723950000,
        axis_rotation_period_hours: 17.2,
        color: "cyan",
        description: "Uranus, the seventh planet from the Sun, is an ice giant known for its unique blue-green color and extreme axial tilt. Named after the Greek god of the sky, Uranus has a diameter of 50,724 km and an orbital period of 30,687 days. It is an ice giant with 27 confirmed moons, including Titania, Oberon, Umbriel, Ariel and Miranda. The average surface temperature on Uranus is around -224°C, making it one of the coldest planets in our solar system. Its atmosphere is primarily composed of hydrogen and helium, with traces of methane that give it its distinctive color. Uranus rotates on its axis every 17.2 hours, but what makes it truly unique is its extreme axial tilt of about 98 degrees. This means that Uranus essentially rolls around the Sun on its side, resulting in extreme seasonal variations during its long orbit. It also has its own set of faint rings, which are composed of ice particles and dust. The planet's unusual characteristics and distant location have made it a fascinating subject of study for astronomers and space enthusiasts alike."
    },
    Neptune: {
        Name: "Neptune",
        Nickname: "Poseidon's Wind",
        type: "ice giant",
        diameter_km: 49244,
        orbital_period_days: 60190,
        moons: 14,
        radius_km: 24622,
        distance_from_sun_km: 4495000000,
        AU: 30.07,
        surface_temperature_c: -214,
        atmosphere_composition: ["hydrogen", "helium", "methane"],
        distance_from_earth_km: 4351000000,
        axis_rotation_period_hours: 16.1,
        color: "blue",
        description: "Neptune, the eighth and farthest planet from the Sun, is an ice giant known for its deep blue color and powerful winds. Named after the Roman god of the sea, Neptune has a diameter of 49,244 km and an orbital period of 60,190 days. It is an ice giant with 14 confirmed moons, including Triton, which is the largest moon in the solar system and has a retrograde orbit. This means that Triton is slowly spiraling inward and will eventually be torn apart by Neptune's gravity. The average surface temperature on Neptune is around -214°C, and its atmosphere is primarily composed of hydrogen and helium, with traces of methane that give it its striking blue color. Neptune rotates on its axis every 16.1 hours, and it has some of the strongest winds in the solar system, reaching speeds of up to 2,100 km/h. Despite being so distant from Earth, Neptune's dynamic atmosphere and intriguing moons have made it a fascinating target for exploration and study in our quest to understand the outer reaches of our solar system."
    },
    Pluto: {
        Name: "Pluto",
        Nickname: "The Dwarf Wanderer",
        type: "dwarf planet",
        diameter_km: 2376,
        orbital_period_days: 90560,
        moons: 5,
        radius_km: 1188.3,
        distance_from_sun_km: 5906000000,
        AU: 39.48,
        surface_temperature_c: -229,
        atmosphere_composition: ["nitrogen", "methane", "carbon_monoxide"],
        distance_from_earth_km: 5906000000,
        axis_rotation_period_hours: 153.3,
        color: "brown",
        description: "Pluto, once considered the ninth planet in our solar system, is now classified as a dwarf planet. Named after the Roman god of the underworld, Pluto has a diameter of 2,376 km and an orbital period of 90,560 days. It has five known moons, with Charon being the largest and most significant one. Charon is about 1212 km across, meaning that it is more than half the width of Pluto itself! The average surface temperature on Pluto is around -229°C, making it one of the coldest objects in our solar system. Its atmosphere is primarily composed of nitrogen, with traces of methane and carbon monoxide. Pluto rotates on its axis every 153.3 hours, which is about 6.4 Earth days. Despite its small size and distant location, Pluto has a complex geology and a surprising variety of surface features, including mountains made of water ice and vast plains of frozen nitrogen. The New Horizons mission provided us with our first close-up look at this distant world in 2015, revealing a fascinating and dynamic landscape that continues to captivate scientists and space enthusiasts alike."
    },
    Moon: {
        Name: "Moon",
        Nickname: "Earth's Companion",
        type: "natural satellite",
        diameter_km: 3474.8,
        orbital_period_days: 27.3,
        moons: 0,
        radius_km: 1737.4,
        distance_from_earth_km: 384400,
        surface_temperature_c: -20,
        atmosphere_composition: ["trace_gases"],
        color: "gray",
        description: "The Moon, Earth's only natural satellite, is a rocky and barren world that has captivated humanity for millennia. It has a diameter of 3,474.8 km and an orbital period of 27.3 days. The Moon has no moons of its own and is located about 384,400 km from Earth. Its surface temperature can vary widely, with daytime temperatures reaching up to 127°C and nighttime temperatures dropping to -173°C. The Moon has a very thin atmosphere composed of trace gases, which is not sufficient to support life as we know it. The Moon's surface is covered in a layer of fine dust and rocky debris called regolith, and it features a variety of geological formations, including craters, mountains, and maria (large, dark plains formed by ancient volcanic activity). The Moon has been a source of inspiration for art, literature, and scientific exploration throughout history. It was the first celestial body beyond Earth to be visited by humans during the Apollo missions, and it continues to be a focus of scientific research and future exploration plans."
    }
};

export default celestial_bodies;